// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: internal/app/proto/balance_total.proto

package generated_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BalanceTotal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IncomeTotal  string `protobuf:"bytes,2,opt,name=income_total,json=incomeTotal,proto3" json:"income_total,omitempty"`
	ExpenseTotal string `protobuf:"bytes,3,opt,name=expense_total,json=expenseTotal,proto3" json:"expense_total,omitempty"`
	Month        string `protobuf:"bytes,4,opt,name=month,proto3" json:"month,omitempty"`
	Year         string `protobuf:"bytes,5,opt,name=year,proto3" json:"year,omitempty"`
	UserId       string `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedBy    string `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt    string `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *BalanceTotal) Reset() {
	*x = BalanceTotal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_app_proto_balance_total_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceTotal) ProtoMessage() {}

func (x *BalanceTotal) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_proto_balance_total_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceTotal.ProtoReflect.Descriptor instead.
func (*BalanceTotal) Descriptor() ([]byte, []int) {
	return file_internal_app_proto_balance_total_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceTotal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BalanceTotal) GetIncomeTotal() string {
	if x != nil {
		return x.IncomeTotal
	}
	return ""
}

func (x *BalanceTotal) GetExpenseTotal() string {
	if x != nil {
		return x.ExpenseTotal
	}
	return ""
}

func (x *BalanceTotal) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *BalanceTotal) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *BalanceTotal) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BalanceTotal) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *BalanceTotal) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type BalanceTotalCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IncomeTotal  string `protobuf:"bytes,1,opt,name=income_total,json=incomeTotal,proto3" json:"income_total,omitempty"`
	ExpenseTotal string `protobuf:"bytes,2,opt,name=expense_total,json=expenseTotal,proto3" json:"expense_total,omitempty"`
	Month        string `protobuf:"bytes,3,opt,name=month,proto3" json:"month,omitempty"`
	Year         string `protobuf:"bytes,4,opt,name=year,proto3" json:"year,omitempty"`
}

func (x *BalanceTotalCreate) Reset() {
	*x = BalanceTotalCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_app_proto_balance_total_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceTotalCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceTotalCreate) ProtoMessage() {}

func (x *BalanceTotalCreate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_proto_balance_total_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceTotalCreate.ProtoReflect.Descriptor instead.
func (*BalanceTotalCreate) Descriptor() ([]byte, []int) {
	return file_internal_app_proto_balance_total_proto_rawDescGZIP(), []int{1}
}

func (x *BalanceTotalCreate) GetIncomeTotal() string {
	if x != nil {
		return x.IncomeTotal
	}
	return ""
}

func (x *BalanceTotalCreate) GetExpenseTotal() string {
	if x != nil {
		return x.ExpenseTotal
	}
	return ""
}

func (x *BalanceTotalCreate) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *BalanceTotalCreate) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

type CreateBalanceTotalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *BalanceTotalCreate `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateBalanceTotalRequest) Reset() {
	*x = CreateBalanceTotalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_app_proto_balance_total_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBalanceTotalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBalanceTotalRequest) ProtoMessage() {}

func (x *CreateBalanceTotalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_proto_balance_total_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBalanceTotalRequest.ProtoReflect.Descriptor instead.
func (*CreateBalanceTotalRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_proto_balance_total_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBalanceTotalRequest) GetData() *BalanceTotalCreate {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateBalanceTotalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data    *BalanceTotal `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateBalanceTotalResponse) Reset() {
	*x = CreateBalanceTotalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_app_proto_balance_total_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBalanceTotalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBalanceTotalResponse) ProtoMessage() {}

func (x *CreateBalanceTotalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_proto_balance_total_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBalanceTotalResponse.ProtoReflect.Descriptor instead.
func (*CreateBalanceTotalResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_proto_balance_total_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBalanceTotalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateBalanceTotalResponse) GetData() *BalanceTotal {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_internal_app_proto_balance_total_proto protoreflect.FileDescriptor

var file_internal_app_proto_balance_total_proto_rawDesc = []byte{
	0x0a, 0x26, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x70, 0x66, 0x74, 0x22, 0xe7, 0x01,
	0x0a, 0x0c, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73,
	0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04,
	0x79, 0x65, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x86, 0x01, 0x0a, 0x12, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73,
	0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04,
	0x79, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72,
	0x22, 0x48, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x66,
	0x74, 0x2e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5d, 0x0a, 0x1a, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x70, 0x66, 0x74, 0x2e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x1e, 0x5a, 0x1c, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_internal_app_proto_balance_total_proto_rawDescOnce sync.Once
	file_internal_app_proto_balance_total_proto_rawDescData = file_internal_app_proto_balance_total_proto_rawDesc
)

func file_internal_app_proto_balance_total_proto_rawDescGZIP() []byte {
	file_internal_app_proto_balance_total_proto_rawDescOnce.Do(func() {
		file_internal_app_proto_balance_total_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_app_proto_balance_total_proto_rawDescData)
	})
	return file_internal_app_proto_balance_total_proto_rawDescData
}

var file_internal_app_proto_balance_total_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_app_proto_balance_total_proto_goTypes = []any{
	(*BalanceTotal)(nil),               // 0: pft.BalanceTotal
	(*BalanceTotalCreate)(nil),         // 1: pft.BalanceTotalCreate
	(*CreateBalanceTotalRequest)(nil),  // 2: pft.CreateBalanceTotalRequest
	(*CreateBalanceTotalResponse)(nil), // 3: pft.CreateBalanceTotalResponse
}
var file_internal_app_proto_balance_total_proto_depIdxs = []int32{
	1, // 0: pft.CreateBalanceTotalRequest.data:type_name -> pft.BalanceTotalCreate
	0, // 1: pft.CreateBalanceTotalResponse.data:type_name -> pft.BalanceTotal
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_app_proto_balance_total_proto_init() }
func file_internal_app_proto_balance_total_proto_init() {
	if File_internal_app_proto_balance_total_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_app_proto_balance_total_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*BalanceTotal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_app_proto_balance_total_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BalanceTotalCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_app_proto_balance_total_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateBalanceTotalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_app_proto_balance_total_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateBalanceTotalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_app_proto_balance_total_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_app_proto_balance_total_proto_goTypes,
		DependencyIndexes: file_internal_app_proto_balance_total_proto_depIdxs,
		MessageInfos:      file_internal_app_proto_balance_total_proto_msgTypes,
	}.Build()
	File_internal_app_proto_balance_total_proto = out.File
	file_internal_app_proto_balance_total_proto_rawDesc = nil
	file_internal_app_proto_balance_total_proto_goTypes = nil
	file_internal_app_proto_balance_total_proto_depIdxs = nil
}
