// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: internal/app/proto/balance_total.proto

package generated_proto

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// BalanceTotalServiceClient is the client API for BalanceTotalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BalanceTotalServiceClient interface {
}

type balanceTotalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBalanceTotalServiceClient(cc grpc.ClientConnInterface) BalanceTotalServiceClient {
	return &balanceTotalServiceClient{cc}
}

// BalanceTotalServiceServer is the server API for BalanceTotalService service.
// All implementations must embed UnimplementedBalanceTotalServiceServer
// for forward compatibility.
type BalanceTotalServiceServer interface {
	mustEmbedUnimplementedBalanceTotalServiceServer()
}

// UnimplementedBalanceTotalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBalanceTotalServiceServer struct{}

func (UnimplementedBalanceTotalServiceServer) mustEmbedUnimplementedBalanceTotalServiceServer() {}
func (UnimplementedBalanceTotalServiceServer) testEmbeddedByValue()                             {}

// UnsafeBalanceTotalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BalanceTotalServiceServer will
// result in compilation errors.
type UnsafeBalanceTotalServiceServer interface {
	mustEmbedUnimplementedBalanceTotalServiceServer()
}

func RegisterBalanceTotalServiceServer(s grpc.ServiceRegistrar, srv BalanceTotalServiceServer) {
	// If the following call pancis, it indicates UnimplementedBalanceTotalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BalanceTotalService_ServiceDesc, srv)
}

// BalanceTotalService_ServiceDesc is the grpc.ServiceDesc for BalanceTotalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BalanceTotalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pft.BalanceTotalService",
	HandlerType: (*BalanceTotalServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "internal/app/proto/balance_total.proto",
}
